//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FroAsyncDB.FroAsyncService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FroAyncType.TaskType", Namespace="http://schemas.datacontract.org/2004/07/FroAsyncSrv.Core")]
    public enum FroAyncTypeTaskType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateData = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateCube = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExecuteSP = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FroAsyncService.IFroAsyncSrv")]
    public interface IFroAsyncSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFroAsyncSrv/AddTask", ReplyAction="http://tempuri.org/IFroAsyncSrv/AddTaskResponse")]
        string AddTask(FroAsyncDB.FroAsyncService.FroAyncTypeTaskType type, int configId, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFroAsyncSrv/AddTask", ReplyAction="http://tempuri.org/IFroAsyncSrv/AddTaskResponse")]
        System.Threading.Tasks.Task<string> AddTaskAsync(FroAsyncDB.FroAsyncService.FroAyncTypeTaskType type, int configId, string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFroAsyncSrvChannel : FroAsyncDB.FroAsyncService.IFroAsyncSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FroAsyncSrvClient : System.ServiceModel.ClientBase<FroAsyncDB.FroAsyncService.IFroAsyncSrv>, FroAsyncDB.FroAsyncService.IFroAsyncSrv {
        
        public FroAsyncSrvClient() {
        }
        
        public FroAsyncSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FroAsyncSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FroAsyncSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FroAsyncSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddTask(FroAsyncDB.FroAsyncService.FroAyncTypeTaskType type, int configId, string email) {
            return base.Channel.AddTask(type, configId, email);
        }
        
        public System.Threading.Tasks.Task<string> AddTaskAsync(FroAsyncDB.FroAsyncService.FroAyncTypeTaskType type, int configId, string email) {
            return base.Channel.AddTaskAsync(type, configId, email);
        }
    }
}
