//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FroAsyncDB.BO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FroAsyncDBEntities : DbContext
    {
        public FroAsyncDBEntities()
            : base("name=FroAsyncDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<update_con_str> update_con_str { get; set; }
        public virtual DbSet<update_op_config> update_op_config { get; set; }
        public virtual DbSet<update_op_dyn> update_op_dyn { get; set; }
        public virtual DbSet<update_op_key> update_op_key { get; set; }
        public virtual DbSet<update_op_conv> update_op_conv { get; set; }
        public virtual DbSet<update_op_log> update_op_log { get; set; }
        public virtual DbSet<app_option> app_option { get; set; }
        public virtual DbSet<update_cube> update_cube { get; set; }
        public virtual DbSet<execute_sp> execute_sp { get; set; }
    }
}
