//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FroAsyncDB.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class execute_sp
    {
        public int exec_id { get; set; }
        public string sp_name { get; set; }
        public Nullable<bool> enable { get; set; }
        public Nullable<int> up_con_id { get; set; }
    
        public virtual update_con_str update_con_str { get; set; }
    }
}
