//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FroAsyncDB.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class update_op_config
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public update_op_config()
        {
            this.update_op_dyn = new HashSet<update_op_dyn>();
            this.update_op_key = new HashSet<update_op_key>();
            this.update_op_conv = new HashSet<update_op_conv>();
            this.update_op_log = new HashSet<update_op_log>();
        }
    
        public int op_id { get; set; }
        public Nullable<int> op_order { get; set; }
        public Nullable<int> src_con_str { get; set; }
        public string src_tbl_name { get; set; }
        public string src_cols { get; set; }
        public string src_filter { get; set; }
        public string src_filter_val { get; set; }
        public Nullable<int> dst_con_str { get; set; }
        public string dst_tbl_name { get; set; }
        public string dst_cols { get; set; }
        public string dst_filter { get; set; }
        public string dst_filter_val { get; set; }
        public bool enable { get; set; }
        public string op_desc { get; set; }
        public Nullable<bool> clear_require { get; set; }
    
        public virtual update_con_str update_con_str { get; set; }
        public virtual update_con_str update_con_str1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<update_op_dyn> update_op_dyn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<update_op_key> update_op_key { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<update_op_conv> update_op_conv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<update_op_log> update_op_log { get; set; }
    }
}
