//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FroAsyncDB.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class update_op_log
    {
        public long op_log { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
        public Nullable<int> op_id { get; set; }
        public string log_result { get; set; }
        public string log_msg { get; set; }
        public Nullable<int> eff_count { get; set; }
    
        public virtual update_op_config update_op_config { get; set; }
    }
}
