SELECT customer_code,customer_name,distribution_center,route_number,sales_district,sales_division,rsm,code26,a_r_customer_code,first_served_date,l5,l7,customer_inactive,date_of_last_service,date_last_invoice,
credit_limit,payment_type,terms_code,last_pay_date,credit_hold,credit_hold_date,customer_balance,customer_payment,price_group,consumer_price_group,promo_plan,channel_code,l4,l6
FROM 
(SELECT 
  'E' + CAST(CUSCUSNUM AS NVARCHAR) + '-' + CAST(CUSCUSCHN AS NVARCHAR) AS customer_code
, CUSCUSNAM AS customer_name
, CASE WHEN CUSDFTDCN = 0 OR CUSDFTDCN = 999 THEN NULL ELSE CUSDFTDCN END AS distribution_center
, CASE WHEN CUSRTENUM = 0 THEN NULL ELSE CUSRTENUM END AS route_number
, CASE WHEN CUSSLSDIS = 0 THEN NULL ELSE CUSSLSDIS END AS sales_district
, CASE WHEN CUSSLSDIV = 0 THEN NULL ELSE CUSSLSDIV END AS sales_division
, CASE WHEN CUSREGNUM = 0 THEN NULL ELSE CUSREGNUM END AS rsm
, CASE WHEN CUSCUSTYP = 0 THEN NULL ELSE CUSCUSTYP END AS code26
, CASE WHEN CUSARCSNM = 0 AND CUSARCHNM = 0 THEN NULL ELSE 'E' + CAST(CUSARCSNM AS NVARCHAR) + '-' + CAST(CUSARCHNM AS NVARCHAR) END AS a_r_customer_code
, CASE WHEN CUSFSRVDE = 0 THEN NULL ELSE convert(datetime,convert(char(8),CUSFSRVDE )) END AS first_served_date
, CASE WHEN CUSBUSTYP = 0 THEN NULL ELSE CUSBUSTYP END AS l5
, CASE WHEN CUSDPTMNT = 0 THEN NULL ELSE CUSDPTMNT END AS l7
, CUSINACTV AS customer_inactive
, CASE WHEN CUSLSRVDE = 0 THEN NULL ELSE convert(datetime,convert(char(8),CUSLSRVDE)) END AS date_of_last_service
, CASE WHEN CUSLIVCDE = 0 THEN NULL ELSE convert(datetime,convert(char(8),CUSLIVCDE)) END AS date_last_invoice
--AR
,CARCRDLMT AS credit_limit
,CASE WHEN CARPAYTYP = 0 THEN NULL ELSE CARPAYTYP END AS payment_type
,CASE WHEN CARTRMCOD = '0' OR CARTRMCOD = '' THEN NULL ELSE CARTRMCOD END AS terms_code
, CASE WHEN CARLPMTDE = 0 THEN NULL ELSE convert(datetime,convert(char(8),CARLPMTDE)) END AS last_pay_date
,CARCRDHLD AS credit_hold
, CASE WHEN CARCRHDTE = 0 THEN NULL ELSE convert(datetime,convert(char(8),CARCRHDTE)) END AS credit_hold_date
,CARCUSBAL AS customer_balance
,CARPAYMNT AS customer_payment
--PRICE
,CPRPRCGRP AS price_group
,CPRPGPRTL AS consumer_price_group
,CPRPLNNUM AS promo_plan
--Ext
,CASE WHEN RMCSEP.CSECHANNL = 0 THEN NULL ELSE RMCSEP.CSECHANNL END AS channel_code
,CASE WHEN RMCSEP.CSESUBDIV = 0 THEN NULL ELSE RMCSEP.CSESUBDIV END AS l4
,CASE WHEN RMCSEP.CSEMRKCOD = 0 THEN NULL ELSE RMCSEP.CSEMRKCOD END AS l6
, CASE 
WHEN CUSCHGDTE >= CARCHGDTE AND CUSCHGDTE >= CPRCHGDTE AND CUSCHGDTE >= CSECHGDTE THEN CUSCHGDTE
WHEN CARCHGDTE >= CUSCHGDTE AND CARCHGDTE >= CPRCHGDTE AND CARCHGDTE >= CSECHGDTE THEN CARCHGDTE
WHEN CPRCHGDTE >= CUSCHGDTE AND CPRCHGDTE >= CARCHGDTE AND CPRCHGDTE >= CSECHGDTE THEN CPRCHGDTE
WHEN CSECHGDTE >= CUSCHGDTE AND CSECHGDTE >= CARCHGDTE AND CSECHGDTE >= CPRCHGDTE THEN CSECHGDTE
ELSE CUSCHGDTE
END AS edit_d
, CASE 
WHEN CUSCHGTIM >= CARCHGTIM AND CUSCHGTIM >= CPRCHGTIM AND CUSCHGTIM >= CSECHGTIM THEN CUSCHGTIM
WHEN CARCHGTIM >= CUSCHGTIM AND CARCHGTIM >= CPRCHGTIM AND CARCHGTIM >= CSECHGTIM THEN CARCHGTIM
WHEN CPRCHGTIM >= CUSCHGTIM AND CPRCHGTIM >= CARCHGTIM AND CPRCHGTIM >= CSECHGTIM THEN CPRCHGTIM
WHEN CSECHGTIM >= CUSCHGTIM AND CSECHGTIM >= CARCHGTIM AND CSECHGTIM >= CPRCHGTIM THEN CSECHGTIM
ELSE CUSCHGTIM
END AS edit_t
FROM CXPRDDTA.RMCUSP 
LEFT OUTER JOIN CXPRDDTA.RMCARP ON CXPRDDTA.RMCUSP.CUSCUSCHN = CXPRDDTA.RMCARP.CARCUSCHN AND CXPRDDTA.RMCUSP.CUSCUSNUM = CXPRDDTA.RMCARP.CARCUSNUM
LEFT OUTER JOIN CXPRDDTA.RMCPRP ON CXPRDDTA.RMCUSP.CUSCUSCHN = CXPRDDTA.RMCPRP.CPRCUSCHN AND CXPRDDTA.RMCUSP.CUSCUSNUM = CXPRDDTA.RMCPRP.CPRCUSNUM
LEFT OUTER JOIN CXPRDDTA.RMCSEP ON CXPRDDTA.RMCUSP.CUSCUSCHN = CXPRDDTA.RMCSEP.CSECUSCHN AND CXPRDDTA.RMCUSP.CUSCUSNUM = CXPRDDTA.RMCSEP.CSECUSNUM
) T