SELECT        dbo.RMSLDP.SLDITMNUM AS [Item Number], dbo.RMSLDP.SLDCUSCHN AS [Chain Number], dbo.RMSLDP.SLDCUSNUM AS [Customer Number], 
dbo.RMSLDP.SLDDELDTE AS [Delivery Date], dbo.RMSLDP.SLDTCKNUM AS [Ticket Number], dbo.RMSLDP.SLDSLSNBR AS [Sales Number], 
dbo.RMSLDP.SLDSLSSEQ AS [Sales Detail Sequence Number], dbo.RMSLDP.SLDDTLTYP AS [Sales Detail type], dbo.RMSLDP.SLDSUBCUS AS [Sub-Customer No.], 
dbo.RMSLDP.SLDSLSTYP AS [Sales Type], dbo.RMSLDP.SLDTRNQTY AS [Transaction Quantity], dbo.RMSLDP.SLDTRNPRC AS [Transaction Price], 
dbo.RMSLDP.SLDTRNAMT AS [Transaction Amount], dbo.RMSLDP.SLDTRNDTE AS [Transaction Date], dbo.RMSLDP.SLDORDQTY AS [Order Quantity], 
dbo.RMSLDP.SLDDSCAMT AS [Discount Amount], dbo.RMSLDP.SLDUNTDSC AS [Unit Discount], dbo.RMSLDP.SLDWGTQTY AS [Weight Qty], 
dbo.RMSLDP.SLDCASCOM AS [Case Commission], dbo.RMSLDP.SLDBKRCMM AS [Broker Commission], dbo.RMSLDP.SLDBUYDIS AS [Buying Group Discount], 
dbo.RMSLDP.SLDFRTCHG AS [Freight Charge], dbo.RMSLDP.SLDRETDIS AS [Discount in Lieu of Returns], dbo.RMSLDP.SLDIVCDSC AS [Invoice Discount Amount], 
dbo.RMSLDP.SLDARRDSC AS [A/R Discount Amount], dbo.RMSLDP.SLDPRCOVR AS [Price Override], dbo.RMSLDP.SLDPRCSRC AS [Price Source], 
dbo.RMSLDP.SLDPRCGRP AS [Price Group], dbo.RMSLDP.SLDROYCHG AS [Royalty Charge], dbo.RMSLDP.SLDADVCHG AS [Advertising Charge], 
dbo.RMSLDP.SLDBASPRC AS [Base Price], dbo.RMSLDP.SLDTAXAMT AS [Tax Amount], dbo.RMSLDP.SLDCOMTBL AS [Commission Table #], 
dbo.RMSLDP.SLDDSCUNT AS [Discount Units], dbo.RMSLDP.SLDRESCOD AS [Reason Code], dbo.RMSLDP.SLDSHPQTY AS [Shipped Quantity], 
dbo.RMSLDP.SLDTAXOVR AS [Tax Override Indicator], dbo.RMSLDP.SLDPRCGP1 AS [Price from Group 1], dbo.RMSLDP.SLDPRCGP2 AS [Price from Price Group 2], 
dbo.RMSLDP.SLDPRCCHN AS [Price From Chain], dbo.RMSLDP.SLDPRCCUS AS [Price From Cust], dbo.RMSLDP.SLDINTSLS AS [Internal Sales Type], 
dbo.RMSLDP.SLDUSRSLS AS [User Sales Type], dbo.RMSLDP.SLDCHGUSR AS [Change User], dbo.RMSLDP.SLDCHGDTE AS [Change Date], 
dbo.RMSLDP.SLDCHGTIM AS [Change Time], dbo.RMSLDP.SLDCRTUSR AS [Create User], dbo.RMSLDP.SLDCRTDTE AS [Create Date], 
dbo.RMSLDP.SLDCRTTIM AS [Create Time], dbo.RMSLHP.SLHSLSNBR, dbo.RMSLHP.SLHCUSCHN, dbo.RMSLHP.SLHCUSNUM, dbo.RMSLHP.SLHSUBCUS, 
dbo.RMSLHP.SLHDELDTE, dbo.RMSLHP.SLHTCKNUM, dbo.RMSLHP.SLHDSTREF AS [Distributor Ticket Reference Number], 
dbo.RMSLHP.SLHCHGREF AS [Charge Sls Nbr Ref], dbo.RMSLHP.SLHTCKREF AS [Reference Ticket Number], 
dbo.RMSLHP.SLHUSRREF AS [User Defined Ticket Reference Number], dbo.RMSLHP.SLHDELDAY AS [Delivery Day], dbo.RMSLHP.SLHSLSTYP AS [Sales Pay Type],
dbo.RMSLHP.SLHRTENUM AS [Route Number], dbo.RMSLHP.SLHSUBRTE AS [Sub Route], dbo.RMSLHP.SLHDRVNUM AS [Driver Number], 
dbo.RMSLHP.SLHDSTCTR AS [Distribution Center], dbo.RMSLHP.SLHSLMNUM AS [Salesman Number], dbo.RMSLHP.SLHCOMNUM AS [Company Number], 
dbo.RMSLHP.SLHREGNUM AS [Region Number], dbo.RMSLHP.SLHSUBREG AS [Sub-Region Number], dbo.RMSLHP.SLHSLSDIS AS [Sales District], 
dbo.RMSLHP.SLHSLSDIV AS [Sales Division], dbo.RMSLHP.SLHSUBDIV AS [Sub-Division], dbo.RMSLHP.SLHSECTOR AS [Sector Code], 
dbo.RMSLHP.SLHSUBSEC AS [Sub Sector], dbo.RMSLHP.SLHDPTMNT AS Department, dbo.RMSLHP.SLHGEOREG AS [Geographic Region Code], 
dbo.RMSLHP.SLHGEOSUB AS [Geographic Sub-Region Code], dbo.RMSLHP.SLHSEGMNT AS Segment, dbo.RMSLHP.SLHSUBSEG AS [Sub-Segment], 
dbo.RMSLHP.SLHPURORD AS [Purchase Order Number], dbo.RMSLHP.SLHORDNUM AS [Order Number], dbo.RMSLHP.SLHORDTYP AS [Order Type], 
dbo.RMSLHP.SLHORDDTE AS [Order Date], dbo.RMSLHP.SLHREGRTE AS [Regular Route], dbo.RMSLHP.SLHTOTQTY AS [Total Quantity], 
dbo.RMSLHP.SLHTOTVAL AS [Total Value], dbo.RMSLHP.SLHSLDAMT AS [Sales Amount], dbo.RMSLHP.SLHSLDQTY AS [Sales Quantity], 
dbo.RMSLHP.SLHSLDWQT AS [Sales Weight Qty], dbo.RMSLHP.SLHSLRAMT AS [Buyback Amount], dbo.RMSLHP.SLHSLRQTY AS [Buyback Quantity], 
dbo.RMSLHP.SLHSLRWQT AS [Buyback Weight Qty], dbo.RMSLHP.SLHSLWAMT AS [Dump Amount], dbo.RMSLHP.SLHSLWQTY AS [Dump Quantity], 
dbo.RMSLHP.SLHSLWWQT AS [Dump Weight Qty], dbo.RMSLHP.SLHDSCAMT, dbo.RMSLHP.SLHARRDSC, dbo.RMSLHP.SLHCASCOM, dbo.RMSLHP.SLHBKRCMM, 
dbo.RMSLHP.SLHBUYDIS, dbo.RMSLHP.SLHFRTCHG, dbo.RMSLHP.SLHRETDIS, dbo.RMSLHP.SLHDSCSWT AS [Discount Processing Switch], 
dbo.RMSLHP.SLHSELDTE AS [Invoice Selection Date], dbo.RMSLHP.SLHLODDTE AS [Load Date], dbo.RMSLHP.SLHNGJUPD AS [General Journal Update], 
dbo.RMSLHP.SLHIVCNUM AS [Invoice Number], dbo.RMSLHP.SLHARENTD AS [A/R Entered Date], dbo.RMSLHP.SLHCSHRCV AS [Cash Payments], 
dbo.RMSLHP.SLHORDSRC AS [Order Source], dbo.RMSLHP.SLHROYCHG, dbo.RMSLHP.SLHADVCHG, dbo.RMSLHP.SLHSUPRTE AS [Super Route Number], 
dbo.RMSLHP.SLHTAXAMT, dbo.RMSLHP.SLHFSCYER AS [Fiscal Year], dbo.RMSLHP.SLHFSCWEK AS [Fiscal Week Number], 
dbo.RMSLHP.SLHFSCPER AS [Fiscal Period], dbo.RMSLHP.SLHCUSTYP AS [Customer Type], dbo.RMSLHP.SLHTRNTIM AS [Transaction Time], 
dbo.RMSLHP.SLHSTRTIM AS [Start Time HHMM], dbo.RMSLHP.SLHENDTIM AS [End Time  HHMM], dbo.RMSLHP.SLHVNDCOL AS [Vendor Collection Amount], 
dbo.RMSLHP.SLHVNDCOM AS [Vendor Commission Amount], dbo.RMSLHP.SLHARCHNN AS [A/R Chain Number], 
dbo.RMSLHP.SLHARCUSN AS [A/R Customer Number], dbo.RMSLHP.SLHARSBCS AS [A/R Sub-Customer No.], dbo.RMSLHP.SLHRTLAMT AS [Retail Amount], 
dbo.RMSLHP.SLHHQPAMT AS [Headquarter Amount], dbo.RMSLHP.SLHCOMAMT AS [Commission Amount], dbo.RMSLHP.SLHINVRUN AS [Invoice Run], 
dbo.RMSLHP.SLHPGMCOD AS [Program Name Code], dbo.RMSLHP.SLHORGCHN AS [Chain Number-Originating], 
dbo.RMSLHP.SLHORGCUS AS [Customer Number-Originating], dbo.RMSLHP.SLHREBUPD AS [Rebate Process Date], 
dbo.RMSLHP.SLHSLDTYP AS [Sales Type - HP], dbo.RMSLHP.SLHARRTYP AS [A/R Transaction Type], dbo.RMSLHP.SLHORDDDT AS [Original Order Delivery Date], 
dbo.RMSLHP.SLHCMMUPD AS [Data Structure For Comm Types], dbo.RMSLHP.SLHTAXCOL AS [Tax Collected Amount], 
dbo.RMSLHP.SLHGLSRCD AS [G/L Source Code], dbo.RMSLHP.SLHSERITM AS [Serial Number Item], dbo.RMSLHP.SLHVMITRN AS [VMI Transaction], 
dbo.RMSLHP.SLHSLCQTY, dbo.RMSLHP.SLHSLCAMT, dbo.RMSLHP.SLHSLIQTY, dbo.RMSLHP.SLHSLIAMT, dbo.RMSLHP.SLHREFIDT AS [Invoice Date Referenced], 
dbo.RMSLHP.SLHREFINM AS [Invoice Number  Referenced], dbo.RMSLHP.SLHHWUPDC AS [Century-  Weekyy History Updt], 
dbo.RMSLHP.SLHHWUPDM AS [Month-Weekly History Updt], dbo.RMSLHP.SLHHWUPDW AS [Week#-Weekly History Updt], 
dbo.RMSLHP.SLHHMUPDC AS [Century- Monthly Hist Update], dbo.RMSLHP.SLHHMUPDM AS [Month-Monthly Hist Update], 
dbo.RMSLHP.SLHUSRFL1 AS [User Defined Code 1 - 1 Char], dbo.RMSLHP.SLHUSRFL2 AS [User Defined Code 2 - 1 Char], 
dbo.RMSLHP.SLHUSRFL3 AS [User Defined Code 3 - 1 Char], dbo.RMSLHP.SLHUSRFL4 AS [User Defined Code 4 - 1 Char], 
dbo.RMSLHP.SLHUSRFL5 AS [User Defined Code 5 - 1 Char], dbo.RMSLHP.SLHFOBPNT AS [FOB Point], dbo.RMSLHP.SLHIFCORD AS [Interface Order], 
dbo.RMSLHP.SLHCRDREF AS [Credit reference], dbo.RMSLHP.SLHMLTORD AS [Multiple order flag], dbo.RMSLHP.SLHMCHAMT AS [Total Amount Of Sale To Match], 
dbo.RMSLHP.SLHMCHTAX AS [Total Tax To Match], dbo.RMSLHP.SLHSWTCH1 AS [Switch Variable 1], dbo.RMSLHP.SLHSWTCH2 AS [Switch Variable 2], 
dbo.RMSLHP.SLHSWTCHU AS [User Switch Variable 1], dbo.RMSLHP.SLHCHGUSR, dbo.RMSLHP.SLHCHGDTE, dbo.RMSLHP.SLHCHGTIM, 
dbo.RMSLHP.SLHCRTUSR, dbo.RMSLHP.SLHCRTDTE, dbo.RMSLHP.SLHCRTTIM, dbo.RMSLHP.SLHIVCBCH AS [Invoice Batch Number], 
dbo.RMSLHP.SLHGLBCH AS [GL Batch Number], dbo.RMSLHP.SLHWHSBCH AS [Weekly History Batch Number], 
dbo.RMSLHP.SLHMHSBCH AS [Monthly History Batch Number], dbo.RMSLHP.SLHREBBCH AS [Rebate Processing Batch Number], 
dbo.RMSLHP.SLHMABCH AS [MA Batch Number], dbo.RMSLHP.SLHCHGBCH AS [Charge Batch Number], dbo.RMSLHP.SLHUS1BCH AS [User Batch Number], 
dbo.RMSLHP.SLHUS2BCH AS [User 2 Batch Number], dbo.RMSLHP.SLHUS3BCH AS [User3 Batch Number], dbo.RMSLHP.SLHUNBFLG AS [Unbilled Flag Update], 
dbo.Product.MaterialName, dbo.Product.BaseProduct, dbo.Product.MaterialType, dbo.Product.[Price Point], dbo.Product.Flavor, dbo.Product.Brand, 
dbo.Product.BaseGroup, dbo.Product.ConsumerSegment, dbo.Product.PricePointRang, dbo.Product.Pallet, dbo.Customer.[Name 3 Ar], dbo.Customer.[Name 1 Ar], 
dbo.Customer.L5, dbo.Customer.L6, dbo.Customer.L7, dbo.Route.RouteDescription, dbo.Route.Region, dbo.Route.SubRegion, dbo.Route.RouteClass, 
dbo.Route.SalesDistrict, dbo.Route.SalesDivision, dbo.Route.PrimarySalesman
FROM            dbo.RMSLDP INNER JOIN
dbo.RMSLHP ON dbo.RMSLDP.SLDSLSNBR = dbo.RMSLHP.SLHSLSNBR LEFT OUTER JOIN
dbo.Route ON dbo.RMSLHP.SLHRTENUM = dbo.Route.RouteNumber LEFT OUTER JOIN
dbo.Customer ON dbo.RMSLHP.SLHCUSNUM = dbo.Customer.Customer AND dbo.RMSLHP.SLHCUSCHN = dbo.Customer.ChainNumber LEFT OUTER JOIN
dbo.Product ON dbo.RMSLDP.SLDITMNUM = dbo.Product.ItemNumber
